name: "On Pull Request"

on:
  pull_request:
    paths: ["src/**"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform init
        working-directory: ./src
        run: terraform init"

      - name: Terraform plan
        working-directory: ./src
        run: terraform plan
